# Generated by Django 2.0.7 on 2021-03-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
    ]
