# Generated by Django 2.0.7 on 2021-03-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activate',
            field=models.TextField(default='this is cool!'),
        ),
    ]
